export const LOAD_QUIZ = "LOAD_QUIZ";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const QUESTION_INDEX_SET_SUCCESS = "QUESTION_INDEX_SET_SUCCESS";

export const INCREMENT_CORRECT_ANSWER_COUNT = "INCREMENT_CORRECT_ANSWER_COUNT";
export const RESET_CORRECT_ANSWER_COUNT = "RESET_CORRECT_ANSWER_COUNT";

export const DISPLAY_INFO_MESSAGE = "DISPLAY_INFO_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

export const LOAD_SETTINGS = "LOAD_SETTINGS";
export const SAVE_SETTINGS = "SAVE_SETTINGS";

export const START_QUIZ_TIMER = "START_QUIZ_TIMER";
export const PAUSE_QUIZ_TIMER = "PAUSE_QUIZ_TIMER";
export const RESET_QUIZ_TIMER = "RESET_QUIZ_TIMER";
export const INCREMENT_QUIZ_TIMER = "INCREMENT_QUIZ_TIMER";
