export const LOAD_KANJI_CATEGORIES_SUCCESS = "LOAD_KANJI_CATEGORIES_SUCCESS";
export const LOAD_KATAKANA_CATEGORIES_SUCCESS =
  "LOAD_KATAKANA_CATEGORIES_SUCCESS";
export const LOAD_HIRAGANA_CATEGORIES_SUCCESS =
  "LOAD_HIRAGANA_CATEGORIES_SUCCESS";

export const LOAD_QUIZ = "LOAD_QUIZ";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const QUESTION_INDEX_SET_SUCCESS = "QUESTION_INDEX_SET_SUCCESS";

export const INCREMENT_CORRECT_ANSWER_COUNT = "INCREMENT_CORRECT_ANSWER_COUNT";
export const RESET_CORRECT_ANSWER_COUNT = "RESET_CORRECT_ANSWER_COUNT";

export const DISPLAY_INFO_MESSAGE = "DISPLAY_INFO_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";
