export const LOAD_KANJI_CATEGORIES_SUCCESS = "LOAD_KANJI_CATEGORIES_SUCCESS";
export const LOAD_KATAKANA_CATEGORIES_SUCCESS =
  "LOAD_KATAKANA_CATEGORIES_SUCCESS";
export const LOAD_HIRAGANA_CATEGORIES_SUCCESS =
  "LOAD_HIRAGANA_CATEGORIES_SUCCESS";
export const LOAD_QUIZ = "LOAD_QUIZ";
export const LOAD_QUIZ_SUCCESS = "LOAD_QUIZ_SUCCESS";
export const QUESTION_SET = "QUESTION_SET";
